### ISSUE TITLE
也许可以加个白名单模式

### ISSUE THREAD

**Issue by rebron1900** [TNXG/ProcessReporterWingo#2]
这样应该会避免很多麻烦，在公开状态的同时保护一下隐私？
（毕竟可能要屏蔽的黑名单有点多？）

**Comment by TNXG** [comment]
> 这样应该会避免很多麻烦，在公开状态的同时保护一下隐私？ （毕竟可能要屏蔽的黑名单有点多？）

某种意义上来说上报程序的宗旨就是将目前干的事情显示出去，显然白名单反而会违背这一宗旨。况且Shiro中未收录的信息就不会在前台显示出来（虽然貌似api会显示就是了（~~而且哥们黑名单内容比白名单内容多你是什么本哥么（不是~~

Demo~ Pr Welcome~

**Comment by rebron1900** [comment]
> > 这样应该会避免很多麻烦，在公开状态的同时保护一下隐私？ （毕竟可能要屏蔽的黑名单有点多？）
> 
> 某种意义上来说上报程序的宗旨就是将目前干的事情显示出去，显然白名单反而会违背这一宗旨。况且Shiro中未收录的信息就不会在前台显示出来（虽然貌似api会显示就是了（~而且哥们黑名单内容比白名单内容多你是什么本哥么（不是~
> 
> Demo~ Pr Welcome~

Shiro收录的才显示其实也算是白名单了，我还是直接复用Shiro的清单吧。
