### ISSUE TITLE
感谢大佬的程序，功能已经上线了。

### ISSUE THREAD

**Issue by rebron1900** [TNXG/ProcessReporterWingo#3]
前来报喜！功能已经成功复刻了！我的博客 https://1900.live/

另外这个有没有可以缩小到任务栏的方式？

**Comment by rebron1900** [comment]
另外WindowsStore的版本似乎是在窗口激活的时候才发送Post请求，可以借鉴吗。

**Comment by TNXG** [comment]
> 另外WindowsStore的版本似乎是在窗口激活的时候才发送Post请求，可以借鉴吗。

抱歉现在才看见ww

关于这个问题，Windows系统的桌面及其系统底层皆基于`explorer.exe`，但因为`explorer.exe`本身也是个程序，所以ProcessReporter也会无疑问会将此内容上报，你自行在代码中添加如果程序为`explorer.exe`就停止发送请求的判断条件以做到此功能(๑•́ ₃ •̀๑)ｴｰ

**Comment by TNXG** [comment]
> 前来报喜！功能已经成功复刻了！我的博客 https://1900.live/
> 
> 另外这个有没有可以缩小到任务栏的方式？

正在尝试使用Windows服务的方法来达成此项ʕ•̀ω•́ʔ✧，或许也可以通过写ui的方法来达成此项（All in Electron (๑•́ ₃ •̀๑)

**Comment by rebron1900** [comment]
cool，不知道现在的上报逻辑是什么样的了。
